# Generated by Django 2.2.4 on 2019-09-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('like', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('reply', models.ManyToManyField(blank=True, related_name='reply_comments', to='posts.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='static/posts')),
                ('photobase64', models.TextField(blank=True)),
                ('description', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('reply', models.IntegerField(default=0)),
                ('comments', models.ManyToManyField(blank=True, to='posts.Comment')),
                ('profile', models.ForeignKey(help_text='este es una clave foranea diciendo que los posts pueden tener muchos usuarios', on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
